## Step 1 Data Exploartion & Leading

In [4]:
# import dependencies
import pandas as pd

In [5]:
df = pd.read_csv('Walmart.csv')
df

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48
...,...,...,...,...,...,...,...,...,...,...,...
10046,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,03/08/23,10:10:00,Cash,3.0,0.33
10047,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
10048,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
10049,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48
10050,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,26/09/20,9:48:00,Cash,3.0,0.33

In [6]:
df.shape

(10051, 11)

In [7]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [8]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [11]:
df.isna().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [12]:
df[df.duplicated()]

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
10000,9950,WALM038,Sugar Land,Fashion accessories,$17,1.0,27/11/23,9:15:00,Cash,3.0,0.48
10001,9951,WALM082,Weslaco,Home and lifestyle,$58,2.0,08/07/20,12:39:00,Cash,6.0,0.33
10002,9952,WALM035,San Angelo,Fashion accessories,$76,3.0,02/10/21,16:34:00,Cash,6.0,0.48
10003,9953,WALM084,Schertz,Home and lifestyle,$68,3.0,13/06/21,10:52:00,Cash,5.0,0.33
10004,9954,WALM046,Temple,Fashion accessories,$40,1.0,22/08/20,14:38:00,Cash,6.0,0.48
10005,9955,WALM054,Sherman,Home and lifestyle,$61,3.0,05/12/21,7:46:00,Cash,3.0,0.21
10006,9956,WALM003,San Antonio,Fashion accessories,$17,3.0,29/10/20,7:13:00,Cash,4.0,0.48
10007,9957,WALM029,Round Rock,Home and lifestyle,$53,1.0,20/06/23,13:41:00,Cash,4.0,0.48
10008,9958,WALM084,Schertz,Fashion accessories,$35,2.0,10/04/22,14:58:00,Cash,7.0,0.33
10009,9959,WALM065,Texas City,Home and lifestyle,$36,1.0,11/03/22,10:26:00,Cash,4.0,0.33
10010,9960,WALM054,Sherman,Fashion accessories,$42,1.0,10/12/22,9:56:00,Cash,3.0,0.33
10011,9961,WALM046,Temple,Home and lifestyle,$70,3.0,02/05/22,6:19:00,Cash,3.0,0.48
10012,9962,WALM035,San Angelo,Fashion accessories,$53,2.0,14/08/21,16:01:00,Cash,7.0,0.48
10013,9963,WALM038,Sugar Land,Home and lifestyle,$70,2.0,14/10/20,13:04:00,Cash,6.0,0.48
10014,9964,WALM025,Waco,Fashion accessories,$60,3.0,20/05/21,7:33:00,Cash,7.0,0.48
10015,9965,WALM035,San Angelo,Home and lifestyle,$68,1.0,06/04/23,15:34:00,Cash,6.0,0.48
10016,9966,WALM035,San Angelo,Fashion accessories,$23,1.0,18/04/22,6:01:00,Cash,5.0,0.48
10017,9967,WALM073,Seguin,Home and lifestyle,$76,2.0,09/04/22,11:49:00,Cash,3.0,0.33
10018,9968,WALM025,Waco,Fashion accessories,$85,1.0,25/03/23,14:31:00,Cash,3.0,0.48
10019,9969,WALM058,Port Arthur,Home and lifestyle,$42,3.0,12/04/21,9:38:00,Cash,3.0,0.33
10020,9970,WALM046,Temple,Fashion accessories,$26,2.0,16/04/20,15:23:00,Cash,7.0,0.48
10021,9971,WALM099,Weatherford,Home and lifestyle,$83,1.0,02/11/22,15:54:00,Cash,6.0,0.18
10022,9972,WALM009,Plano,Fashion accessories,$24,1.0,02/03/21,16:53:00,Cash,7.0,0.48
10023,9973,WALM065,Texas City,Home and lifestyle,$53,3.0,29/11/21,8:24:00,Cash,6.0,0.33
10024,9974,WALM065,Texas City,Fashion accessories,$52,1.0,19/02/20,12:40:00,Cash,7.0,0.33
10025,9975,WALM074,Weslaco,Home and lifestyle,$24,3.0,20/06/21,10:18:00,Cash,4.0,0.33
10026,9976,WALM056,Rowlett,Fashion accessories,$71,1.0,22/11/21,15:08:00,Cash,7.0,0.33
10027,9977,WALM029,Round Rock,Home and lifestyle,$55,3.0,19/06/23,11:30:00,Cash,4.0,0.48
10028,9978,WALM099,Weatherford,Fashion accessories,$70,2.0,16/05/22,14:21:00,Cash,4.0,0.18
10029,9979,WALM030,Richardson,Home and lifestyle,$26,2.0,29/08/22,6:06:00,Cash,3.0,0.48
10030,9980,WALM099,Weatherford,Fashion accessories,$46,2.0,28/02/21,13:11:00,Cash,5.0,0.18
10031,9981,WALM055,Waxahachie,Home and lifestyle,$85,1.0,25/07/20,16:29:00,Cash,5.0,0.33
10032,9982,WALM050,Victoria,Fashion accessories,$41,1.0,27/11/20,9:51:00,Credit card,7.0,0.48
10033,9983,WALM038,Sugar Land,Home and lifestyle,$84,1.0,25/04/21,14:35:00,Cash,5.0,0.48
10034,9984,WALM046,Temple,Fashion accessories,$81,2.0,18/09/21,14:55:00,Cash,4.0,0.48
10035,9985,WALM065,Texas City,Home and lifestyle,$59,2.0,05/04/23,9:25:00,Cash,6.0,0.33
10036,9986,WALM050,Victoria,Fashion accessories,$44,2.0,09/03/22,12:34:00,Credit card,5.0,0.48
10037,9987,WALM084,Schertz,Home and lifestyle,$27,2.0,22/08/21,11:58:00,Cash,7.0,0.33
10038,9988,WALM056,Rowlett,Fashion accessories,$23,2.0,23/05/23,16:20:00,Cash,4.0,0.33
10039,9989,WALM056,Rowlett,Home and lifestyle,$83,1.0,22/10/20,12:08:00,Cash,3.0,0.33
10040,9990,WALM086,Rosenberg,Fashion accessories,$56,2.0,02/09/20,12:37:00,Cash,3.0,0.33
10041,9991,WALM074,Weslaco,Home and lifestyle,$35,3.0,09/07/20,6:38:00,Cash,5.0,0.33
10042,9992,WALM087,Waxahachie,Fashion accessories,$48,3.0,09/09/23,10:54:00,Cash,6.0,0.33
10043,9993,WALM073,Seguin,Home and lifestyle,$31,2.0,01/11/23,15:21:00,Cash,5.0,0.33
10044,9994,WALM055,Waxahachie,Fashion accessories,$34,1.0,29/04/23,14:34:00,Cash,6.0,0.33
10045,9995,WALM030,Richardson,Home and lifestyle,$62,1.0,15/02/21,9:04:00,Cash,3.0,0.48
10046,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,03/08/23,10:10:00,Cash,3.0,0.33
10047,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
10048,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
10049,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48
10050,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,26/09/20,9:48:00,Cash,3.0,0.33

In [13]:
df.duplicated().sum()

np.int64(51)

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
# dropping all rows with missing records
df.dropna(inplace=True)

In [17]:
df.isna().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [18]:
df.shape

(9969, 11)

In [21]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [22]:
df['unit_price'].astype(float)

ValueError: could not convert string to float: '$74.69'

In [23]:
df['unit_price'] = df['unit_price'].str.replace('$','')

In [24]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [27]:
df['unit_price'] = df['unit_price'].astype(float)

In [28]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price        float64
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [29]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [30]:
df['total'] = df['unit_price'] * df['quantity']

In [33]:
df.columns = df.columns.str.lower()

In [34]:
from sqlalchemy import create_engine
username = 'root'
password = 'toor'
host = 'localhost'
port = 3306
database = 'walmart'
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

df.to_sql(
    name='walmart_sales',
    con=engine,
    if_exists='replace',
    index=False
)

9969